# Stage 1 model

In [1]:
import pandas as pd
import plotly.express as px

from rich import print

from ambdes import Model, Runner, SimConfig, ArrivalConfig, TimesConfig

## Run model for 100 minutes with log messages

TODO: Convert this into logging tests which compare patient results with record in the vidigi logger.

In [2]:
arrival_config = ArrivalConfig(arrival_csv="data/arrivals.csv")
display(arrival_config.arrival_df)
display(arrival_config.nspp_df)

           C1   C2   C3  C4
monday     25  310  180  40
tuesday    24  295  170  38
wednesday  24  295  170  38
thursday   24  295  170  38
friday     25  305  178  40
saturday   28  340  200  45
sunday     27  330  195  43

      t  mean_iat
0     0  2.594595
1  1440  2.732448
2  2880  2.732448
3  4320  2.732448
4  5760  2.627737
5  7200  2.349103
6  8640  2.420168

In [3]:
times_config = TimesConfig(times_csv="data/times.csv")

In [4]:
times_config.lognormal_config("travel_to_scene")

{'C1': {'class_name': 'Lognormal', 'params': {'mean': 8, 'stdev': 5}},
 'C2': {'class_name': 'Lognormal', 'params': {'mean': 10, 'stdev': 5}},
 'C3': {'class_name': 'Lognormal', 'params': {'mean': 12, 'stdev': 5}},
 'C4': {'class_name': 'Lognormal', 'params': {'mean': 12, 'stdev': 5}}}

In [5]:
config = SimConfig(
    arrival_config=arrival_config,
    times_config=times_config
)
config.n_ambulances = 1

In [6]:
print(config.dist_config)

{
    'call_arrival': {
        'class_name': 'NSPPThinning',
        'params': {
            'data':       t  mean_iat
0     0  2.594595
1  1440  2.732448
2  2880  2.732448
3  4320  2.732448
4  5760  2.627737
5  7200  2.349103
6  8640  2.420168
        }
    },
    'call_category': {
        'class_name': 'DiscreteEmpirical',
        'params': {
            'values': Index(['C1', 'C2', 'C3', 'C4'], dtype='object'),
            'freq': array([0.04547757, 0.5576737 , 0.32441131, 0.07243742])
        }
    },
    'time_to_scene': {
        'C1': {'class_name': 'Lognormal', 'params': {'mean': 8, 'stdev': 5}},
        'C2': {'class_name': 'Lognormal', 'params': {'mean': 10, 'stdev': 5}},
        'C3': {'class_name': 'Lognormal', 'params': {'mean': 12, 'stdev': 5}},
        'C4': {'class_name': 'Lognormal', 'params': {'mean': 12, 'stdev': 5}}
    },
    'on_scene_time': {
        'C1': {'class_name': 'Lognormal', 'params': {'mean': 44, 'stdev': 5}},
        'C2': {'class_name': 'Lognormal', 'params': {'mean': 46, 'stdev': 5}},
        'C3': {'class_name': 'Lognormal', 'params': {'mean': 48, 'stdev': 5}},
        'C4': {'class_name': 'Lognormal', 'params': {'mean': 50, 'stdev': 5}}
    },
    'time_to_hospital': {
        'C1': {'class_name': 'Lognormal', 'params': {'mean': 8, 'stdev': 5}},
        'C2': {'class_name': 'Lognormal', 'params': {'mean': 10, 'stdev': 5}},
        'C3': {'class_name': 'Lognormal', 'params': {'mean': 12, 'stdev': 5}},
        'C4': {'class_name': 'Lognormal', 'params': {'mean': 12, 'stdev': 5}}
    },
    'handover_time': {
        'C1': {'class_name': 'Lognormal', 'params': {'mean': 15, 'stdev': 5}},
        'C2': {'class_name': 'Lognormal', 'params': {'mean': 22, 'stdev': 5}},
        'C3': {'class_name': 'Lognormal', 'params': {'mean': 40, 'stdev': 5}},
        'C4': {'class_name': 'Lognormal', 'params': {'mean': 45, 'stdev': 5}}
    },
    'wrap_up_time': {
        'C1': {'class_name': 'Lognormal', 'params': {'mean': 5, 'stdev': 2}},
        'C2': {'class_name': 'Lognormal', 'params': {'mean': 5, 'stdev': 2}},
        'C3': {'class_name': 'Lognormal', 'params': {'mean': 5, 'stdev': 2}},
        'C4': {'class_name': 'Lognormal', 'params': {'mean': 5, 'stdev': 2}}
    }
}

In [7]:
model = Model(run_number=0, config=config)
print(model.dists)

{
    'call_arrival': NSPPThinning(data=      t  mean_iat
0     0  2.594595
1  1440  2.732448
2  2880  2.732448
3  4320  2.732448
4  5760  2..., interval=1440.0),
    'call_category': Discrete(values=[C1, C2, C3, ...], freq=[0.04547757478889612, 0.5576737006163818,
0.32441130636504795, ...]),
    'handover_time': {
        'C1': Lognormal(mean=15, stdev=5),
        'C2': Lognormal(mean=22, stdev=5),
        'C3': Lognormal(mean=40, stdev=5),
        'C4': Lognormal(mean=45, stdev=5)
    },
    'on_scene_time': {
        'C1': Lognormal(mean=44, stdev=5),
        'C2': Lognormal(mean=46, stdev=5),
        'C3': Lognormal(mean=48, stdev=5),
        'C4': Lognormal(mean=50, stdev=5)
    },
    'time_to_hospital': {
        'C1': Lognormal(mean=8, stdev=5),
        'C2': Lognormal(mean=10, stdev=5),
        'C3': Lognormal(mean=12, stdev=5),
        'C4': Lognormal(mean=12, stdev=5)
    },
    'time_to_scene': {
        'C1': Lognormal(mean=8, stdev=5),
        'C2': Lognormal(mean=10, stdev=5),
        'C3': Lognormal(mean=12, stdev=5),
        'C4': Lognormal(mean=12, stdev=5)
    },
    'wrap_up_time': {
        'C1': Lognormal(mean=5, stdev=2),
        'C2': Lognormal(mean=5, stdev=2),
        'C3': Lognormal(mean=5, stdev=2),
        'C4': Lognormal(mean=5, stdev=2)
    }
}

In [8]:
model.dists["time_to_scene"]["C1"].sample()

3.940894139077947

In [9]:
model.run()

In [10]:
log = model.logger.to_dataframe()

In [11]:
print(model.patients[0].__dict__)
log[log["entity_id"] == 1]

{'patient_id': 1, 'category': 'C2', 'call_timestamp': 102.73144260373427, 'response_time': None}

,entity_id,event_type,event,time,run_number,resource_id
0,1,arrival_departure,arrival,2.412895,0,NaN
1,1,queue,ambulance_wait_begins,2.412895,0,NaN
2,1,resource_use,ambulance_assigned,2.412895,0,1.0
89,1,arrival_departure,arrival,102.731443,0,NaN
90,1,queue,ambulance_wait_begins,102.731443,0,NaN
117,1,resource_use_end,ambulance_available,123.378454,0,1.0
118,1,arrival_departure,depart,123.378454,0,NaN

In [12]:
print(model.patients[1].__dict__)
log[log["entity_id"] == 2]

{'patient_id': 2, 'category': 'C2', 'call_timestamp': 104.65263046718476, 'response_time': None}

,entity_id,event_type,event,time,run_number,resource_id
3,2,arrival_departure,arrival,4.367052,0,NaN
4,2,queue,ambulance_wait_begins,4.367052,0,NaN
91,2,arrival_departure,arrival,104.652630,0,NaN
92,2,queue,ambulance_wait_begins,104.652630,0,NaN
119,2,resource_use,ambulance_assigned,123.378454,0,1.0

## Run model for longer and inspect patient times

In [13]:
config = SimConfig(
    arrival_config=arrival_config,
    times_config=times_config,
    warm_up_period=0,
    data_collection_period=10080,  # One week
)
model = Model(run_number=0, config=config)
model.run()

In [14]:
df = pd.DataFrame(
    {
        "response_time": [p.response_time for p in model.patients],
        "category": [p.category for p in model.patients],
    }
)

fig = px.histogram(
    df,
    x="response_time",
    facet_col="category",
    nbins=50,
    category_orders={"category": ["C1", "C2", "C3", "C4"]},
    labels={
        "response_time": "Response time (minutes)",
        "category": "Category",
    },
    title="Distribution of response times by category",
)

# fig.update_yaxes(
#    matches=None,
#    showticklabels=True,
# )
fig.layout.yaxis.title.text = "Number of patients"

fig.show()

In [15]:
for cat in ["C1", "C2", "C3", "C4"]:
    fig = px.histogram(
        df[df["category"] == cat],
        x="response_time",
        nbins=20,
        title=f"Response times: {cat}",
        labels={"response_time": "Response time (minutes)"},
    )
    fig.update_yaxes(title_text="Number of patients")
    fig.show()

## Average results

In [16]:
runner = Runner(config)

In [17]:
results = runner.run_reps()

/home/amy/Documents/ambulance/ambdes/src/ambdes/results.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([summary, utilisation], ignore_index=True)
/home/amy/Documents/ambulance/ambdes/src/ambdes/results.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([summary, utilisation], ignore_index=True)
/home/amy/Documents/ambulance/ambdes/src/ambdes/results.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([summary, utilisation], ignore_index=True)
/home/amy/Documents/ambulance/ambdes/src/ambdes/results.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([summary, utilisation], ignore_index=True)
/home/amy/Documents/ambulance/ambdes/src/ambdes/results.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([summary, utilisation], ignore_index=True)

In [18]:
results["patients"]

       run  patient_id category  call_timestamp  response_time
0        0           1       C3        0.314790       7.500451
1        0           2       C2        7.176539       6.947597
2        0           3       C3        7.501221       9.439192
3        0           4       C2       10.980236      13.586722
4        0           5       C3       11.564670      17.280425
...    ...         ...      ...             ...            ...
19522    4        4038       C2    10066.344734      13.529081
19523    4        4039       C2    10069.372803       6.205357
19524    4        4040       C2    10071.787917            NaN
19525    4        4041       C2    10078.650292            NaN
19526    4        4042       C2    10079.206482            NaN

[19527 rows x 5 columns]

In [19]:
results["run"]

   category n_patients  mean_response_time  run  mean_utilisation
0        C1        185            8.135948    0               NaN
1        C2       2190            9.856775    0               NaN
2        C3       1246           12.075406    0               NaN
3        C4        295           11.775846    0               NaN
4       all       <NA>                 NaN    0          0.127492
5        C1        166            8.680097    1               NaN
6        C2       2060           10.044687    1               NaN
7        C3       1389           12.009423    1               NaN
8        C4        282           12.291636    1               NaN
9       all       <NA>                 NaN    1          0.128437
10       C1        179            8.659564    2               NaN
11       C2       2148            9.955434    2               NaN
12       C3       1271           12.219287    2               NaN
13       C4        304           12.062379    2               NaN
14      all       <NA>                 NaN    2          0.127487
15       C1        159            8.029599    3               NaN
16       C2       2142           10.073489    3               NaN
17       C3       1213           12.092287    3               NaN
18       C4        256           11.590807    3               NaN
19      all       <NA>                 NaN    3          0.122553
20       C1        187            8.215910    4               NaN
21       C2       2305           10.080835    4               NaN
22       C3       1268           11.952313    4               NaN
23       C4        282           11.853980    4               NaN
24      all       <NA>                 NaN    4          0.131609

In [20]:
results["overall"]

  category mean_n_patients  mean_response_time  mean_utilisation
0       C1           175.2            8.344223               NaN
1       C2          2169.0           10.002244               NaN
2       C3          1277.4           12.069743               NaN
3       C4           283.8           11.914930               NaN
4      all             NaN                 NaN          0.127515

In [21]:
config.n_ambulances = 1
config.data_collection_period = 50_000
config.log_to_console = False
runner = Runner(config)
results = runner.run_single(run_number=0)

/home/amy/Documents/ambulance/ambdes/src/ambdes/results.py:212: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  return pd.concat([summary, utilisation], ignore_index=True)

In [22]:
results["run"]

  category n_patients  mean_response_time  run  mean_utilisation
0       C1        912        21318.236835    0               NaN
1       C2      10676        24679.104326    0               NaN
2       C3       6060        23995.661146    0               NaN
3       C4       1367        25140.891280    0               NaN
4      all       <NA>                 NaN    0          0.999986

In [23]:
results["patients"].head(20)

    run  patient_id category  call_timestamp  response_time
0     0           1       C3        0.683523       7.500451
1     0           2       C2        2.505478     126.091202
2     0           3       C3       10.969963     198.456506
3     0           4       C2       11.275438     311.200116
4     0           5       C3       15.323526     404.528564
5     0           6       C3       15.504300     531.110482
6     0           7       C2       15.787397     645.439876
7     0           8       C3       18.690178     741.784383
8     0           9       C2       19.321938     852.320599
9     0          10       C4       20.202594     960.281670
10    0          11       C3       20.939325    1071.206286
11    0          12       C3       21.875284    1189.730465
12    0          13       C2       23.170896    1328.822807
13    0          14       C3       25.399811    1427.243092
14    0          15       C2       26.466044    1544.336122
15    0          16       C1       33.360358    1615.757443
16    0          17       C2       33.674696    1718.720332
17    0          18       C3       34.263001    1823.906138
18    0          19       C2       34.481231    1936.239956
19    0          20       C2       35.497297    2027.873082

In [24]:
results["model"].logger.to_dataframe().head(30)

,entity_id,event_type,event,time,run_number,resource_id
0,1,arrival_departure,arrival,0.683523,0,NaN
1,1,queue,ambulance_wait_begins,0.683523,0,NaN
2,1,resource_use,ambulance_assigned,0.683523,0,1.0
3,2,arrival_departure,arrival,2.505478,0,NaN
4,2,queue,ambulance_wait_begins,2.505478,0,NaN
5,3,arrival_departure,arrival,10.969963,0,NaN
6,3,queue,ambulance_wait_begins,10.969963,0,NaN
7,4,arrival_departure,arrival,11.275438,0,NaN
8,4,queue,ambulance_wait_begins,11.275438,0,NaN
9,5,arrival_departure,arrival,15.323526,0,NaN
10,5,queue,ambulance_wait_begins,15.323526,0,NaN
11,6,arrival_departure,arrival,15.504300,0,NaN
12,6,queue,ambulance_wait_begins,15.504300,0,NaN
13,7,arrival_departure,arrival,15.787397,0,NaN
14,7,queue,ambulance_wait_begins,15.787397,0,NaN
15,8,arrival_departure,arrival,18.690178,0,NaN
16,8,queue,ambulance_wait_begins,18.690178,0,NaN
17,9,arrival_departure,arrival,19.321938,0,NaN
18,9,queue,ambulance_wait_begins,19.321938,0,NaN
19,10,arrival_departure,arrival,20.202594,0,NaN
20,10,queue,ambulance_wait_begins,20.202594,0,NaN
21,11,arrival_departure,arrival,20.939325,0,NaN
22,11,queue,ambulance_wait_begins,20.939325,0,NaN
23,12,arrival_departure,arrival,21.875284,0,NaN
24,12,queue,ambulance_wait_begins,21.875284,0,NaN
25,13,arrival_departure,arrival,23.170896,0,NaN
26,13,queue,ambulance_wait_begins,23.170896,0,NaN
27,14,arrival_departure,arrival,25.399811,0,NaN
28,14,queue,ambulance_wait_begins,25.399811,0,NaN
29,15,arrival_departure,arrival,26.466044,0,NaN